package fuck;
// Generated Dec 11, 2016 3:12:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Ordonnancemedicaments generated by hbm2java
 */
public class Ordonnancemedicaments  implements java.io.Serializable {


     private OrdonnancemedicamentsId id;
     private Medicament medicament;
     private Ordonnance ordonnance;
     private BigDecimal nbboites;

    public Ordonnancemedicaments() {
    }

	
    public Ordonnancemedicaments(OrdonnancemedicamentsId id, Medicament medicament, Ordonnance ordonnance) {
        this.id = id;
        this.medicament = medicament;
        this.ordonnance = ordonnance;
    }
    public Ordonnancemedicaments(OrdonnancemedicamentsId id, Medicament medicament, Ordonnance ordonnance, BigDecimal nbboites) {
       this.id = id;
       this.medicament = medicament;
       this.ordonnance = ordonnance;
       this.nbboites = nbboites;
    }
   
    public OrdonnancemedicamentsId getId() {
        return this.id;
    }
    
    public void setId(OrdonnancemedicamentsId id) {
        this.id = id;
    }
    public Medicament getMedicament() {
        return this.medicament;
    }
    
    public void setMedicament(Medicament medicament) {
        this.medicament = medicament;
    }
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }
    public BigDecimal getNbboites() {
        return this.nbboites;
    }
    
    public void setNbboites(BigDecimal nbboites) {
        this.nbboites = nbboites;
    }




}


