package fuck;
// Generated Dec 11, 2016 3:12:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordonnance generated by hbm2java
 */
public class Ordonnance  implements java.io.Serializable {


     private BigDecimal numord;
     private String recommandations;
     private String type;
     private Date datec;
     private BigDecimal nbrmedicaments;
     private Set consultations = new HashSet(0);
     private Set ordonnancechirurgies = new HashSet(0);
     private Set ordonnancemedicamentses = new HashSet(0);

    public Ordonnance() {
    }

	
    public Ordonnance(BigDecimal numord) {
        this.numord = numord;
    }
    public Ordonnance(BigDecimal numord, String recommandations, String type, Date datec, BigDecimal nbrmedicaments, Set consultations, Set ordonnancechirurgies, Set ordonnancemedicamentses) {
       this.numord = numord;
       this.recommandations = recommandations;
       this.type = type;
       this.datec = datec;
       this.nbrmedicaments = nbrmedicaments;
       this.consultations = consultations;
       this.ordonnancechirurgies = ordonnancechirurgies;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
    }
   
    public BigDecimal getNumord() {
        return this.numord;
    }
    
    public void setNumord(BigDecimal numord) {
        this.numord = numord;
    }
    public String getRecommandations() {
        return this.recommandations;
    }
    
    public void setRecommandations(String recommandations) {
        this.recommandations = recommandations;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }
    public BigDecimal getNbrmedicaments() {
        return this.nbrmedicaments;
    }
    
    public void setNbrmedicaments(BigDecimal nbrmedicaments) {
        this.nbrmedicaments = nbrmedicaments;
    }
    public Set getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }
    public Set getOrdonnancechirurgies() {
        return this.ordonnancechirurgies;
    }
    
    public void setOrdonnancechirurgies(Set ordonnancechirurgies) {
        this.ordonnancechirurgies = ordonnancechirurgies;
    }
    public Set getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }
    
    public void setOrdonnancemedicamentses(Set ordonnancemedicamentses) {
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }




}


