package fuck;
// Generated Dec 11, 2016 3:12:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Typechirurgie generated by hbm2java
 */
public class Typechirurgie  implements java.io.Serializable {


     private BigDecimal idtype;
     private String nom;
     private String description;
     private Set specialisationsalles = new HashSet(0);
     private Set chirurgies = new HashSet(0);

    public Typechirurgie() {
    }

	
    public Typechirurgie(BigDecimal idtype, String nom) {
        this.idtype = idtype;
        this.nom = nom;
    }
    public Typechirurgie(BigDecimal idtype, String nom, String description, Set specialisationsalles, Set chirurgies) {
       this.idtype = idtype;
       this.nom = nom;
       this.description = description;
       this.specialisationsalles = specialisationsalles;
       this.chirurgies = chirurgies;
    }
   
    public BigDecimal getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(BigDecimal idtype) {
        this.idtype = idtype;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getSpecialisationsalles() {
        return this.specialisationsalles;
    }
    
    public void setSpecialisationsalles(Set specialisationsalles) {
        this.specialisationsalles = specialisationsalles;
    }
    public Set getChirurgies() {
        return this.chirurgies;
    }
    
    public void setChirurgies(Set chirurgies) {
        this.chirurgies = chirurgies;
    }




}


